title = "Molecule"
baseURL = "http://www.scalamolecule.org/"
languageCode = "en-us"
metaDataFormat = "yaml"
pygmentsUseClasses=true
uglifyUrls = false
disablePathToLower = true
relativeURLs = true
canonifyURLs = true


[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[[menu.main]]
    weight = 10
    name = "Intro"
    identifier = "intro"
    url = "/intro/"


[[menu.main]]
    weight = 30
    name = "Setup"
    identifier = "setup"
    url = "/setup/"


[[menu.main]]
    weight = 40
    name = "Documentation"
    identifier = "documentation"
    url = "/documentation/"

#[[menu.main]]
#    weight = 50
#    name = "Resources"
#    identifier = "resources"
#    url = "/resources/"

#[[menu.main]]
#    weight = 20
#    parent = "resources"
#    name = "ScalaDocs"
#    identifier = "docs"
#    url = "https://javadoc.io/doc/org.scalamolecule/molecule_2.13/latest/index.html"
#
#[[menu.main]]
#    weight = 210
#    parent = "resources"
#    name = "Changelog"
#    identifier = "changelog"
#    url = "/changelog"


#[[menu.main]]
#    weight = 50
#    name = "Deploy"
#    identifier = "deploy"
#    url = "/deploy/"
#
#
#[[menu.main]]
#    name = "Admin"
#    weight = 60
#    identifier = "admin"
#    url = "/admin/"
#
[[menu.main]]
    weight = 70
    name = "Dev"
    identifier = "dev"
    url = "/dev/"
#
#
#[[menu.main]]
#    name = "Blog"
#    weight = 80
#    identifier = "blog"
#    url = "/blog/"

[[menu.main]]
    name = "Community"
    weight = 90
    identifier = "community"
    url = "/community/"




